#dossier a analyser

filter:
    path: [src/*]
    excluded_paths: [vendor/*,tests/*]

#configuration des outils
tools:
    php_mess_detector: true
    php_code_sniffer: true
    php_pdepend: true
    php_analyser: true
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]